FROM golang:1.4-cross
MAINTAINER Tobias Gesellchen <tobias@gesellix.de> (@gesellix)

WORKDIR /usr/src/app
COPY . /usr/src/app

ENV GOBIN $GOPATH/bin
RUN go get -d -v; go install -v

RUN for GOOS in darwin linux; do \
      export GOOS; \
      for GOARCH in 386 amd64; do \
        export GOARCH; \
        go build -v -o mini-dns-$GOOS-$GOARCH; \
      done \
    done

CMD [ "ls", "-lisah" ]
